### ISSUE TITLE
Support yolov11

### ISSUE THREAD

**Issue by alvises** [poeticoding/yolo_elixir#3]

**Comment by marceloreichert** [comment]
I have a PR ready to load any version.
I messed up and added codes from the previous PR together. So I will wait for a response from the previous one to present the new one.

**Comment by alvises** [comment]
Hi @marceloreichert, thank you for your interest in this project 💜 I already have code to load all the ultralytics models, I'm just spend some time extending it to make it independent from input and output size (not fixed to 84x8400 shape). I'll probably going to rename the module from `yolo8` to `ultralytics`, but still trying to see the direction to take.

Going to check out your PR asap 🙏

**Comment by alvises** [comment]
closing this, since yolov11 is now supported by v0.1.2
